---
title: "Propensity Score Analysis (PSA)"
# subtitle: "why we use it and what does it provide"
author: "王　超辰 | Chaochen Wang"
date: "2019-12-13(tentative) 17:00~18:00 @CSS"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      countdown: 60000
      highlightStyle: github
      highlightLines: true
      highlightSpans: true
      countIncrementalSlides: false
---


class: middle
# Objectives

- Revision about causal inference framework and terminologies.

- Introduction of Propensity Score Analysis (PSA).  

- Understand the **pre-assumptions** that required for PSA.

- Discuss the ways of using Propensity Scores. 

- Understand that PSA is not **omnipotent**

???



---
class: middle, center, inverse

## Some background before PSA


---
class: middle

## What do me mean by <br>"causal inference"? (1)


- Most data analysis in medical research (or in other area) has a central aim - to learn about **cause-effect relationships**. 

    - Does the treatment work? 
    - How harmful is the exposure? 
    - How effective would the policy be and why?
    
    
---
class: middle

## What do me mean by <br>"causal inference"? (2)

- Randomised studies are **randomised** precisely to make causal inference more reliable. 

- When randomisation is not feasible, we still wish to make inferences about effects of causes. 

- However, most medical studies can only be interpreted as *"associations"* rather than causal effect. 


---
class: middle

## Example


Anaemic patients undergoing hip replacement operation might benefit from receiving an **intravenous iron supplement** prior to surgery. 

- Data collected in one hospital on all anaemic patients undergoing a hip replacement operation between 2009 and 2014. 

- $X$:  **intravenous iron supplement**, yes or no
- $Y$: 90 days survival after operation, alive or dead

---
class: middle 

### Other data collected in the example: 

- Age, gender, co-morbidities (CVD, diabetes, renal disease);

- Severity of anaemia;

- Operation types;

- Whether or not transfusion needed during operation;

- Length of stay in hospital;

---
class: middle

## Traditional Approach - crude 

- We start by looking at a 2 $\times$ 2 table:


```{r echo=FALSE}
my_tbl <- tibble::tribble(
~cc, ~c0,  ~X0, ~X1,
  "FeIV",           0, 9206, 376,
  "FeIV",           1, 7365, 312
  )

names(my_tbl) <- c("", "", "0", "1")

require(knitr)
require(kableExtra)
kable_styling(
              kable(my_tbl, digits = 3, row.names = FALSE, align = "c",
              caption = NULL, format = "html"),
        bootstrap_options = c("striped", "hover", "condensed"),
        position = "center", full_width = FALSE) %>% 
  add_header_above(c(" "= 2, "Death90" = 2)) %>% 
  column_spec(1:2, bold = T) %>%
  collapse_rows(1, valign = "middle")
```


- Estimated log odds ratio $= \log(\frac{312\times9206}{376\times7365}) = 0.04, 95\% \text{CI: } -0.12, 0.19$ 

---
class: middle
## Traditional Approach - crude 

- What are we estimating here? The **estimand**<sup>1</sup> is 

$$
\begin{aligned}
\log\text{OR}_{Y|X} & = \log{\frac{\text{Pr}(Y = 1 | X = 1)}{1- \text{Pr}(Y = 1 | X = 1)}} \\
                    & \;\;\;\;\;\;\;\;\; - \log{\frac{\text{Pr}(Y = 1 | X = 0)}{1- \text{Pr}(Y = 1 | X = 0)}}
\end{aligned}
$$

.footnote[
[1] **Estimand** is defined as the value that we we would like to know, such as "the mean BMI of the population in Japan". This is an unknown but fixed quantity.
]

---
class: middle

## Confounding

- We cannot give $\log\text{OR}_{Y|X}$ a causal interpretation because there is confounding. 
- It is possible that patients provided with intravenous iron were already worse off, masking a truely effect of the exposure. 
- So we change the estimand into conditional logOR: 


$$
\begin{aligned}
\log\text{OR}_{Y|X} & = \log{\frac{\text{Pr}(Y = 1 | X = 1, \textbf{C})}{1- \text{Pr}(Y = 1 | X = 1, \textbf{C})}} \\
                    & \;\;\;\;\;\;\;\;\; - \log{\frac{\text{Pr}(Y = 1 | X = 0, \textbf{C})}{1- \text{Pr}(Y = 1 | X = 0, \textbf{C})}}
\end{aligned}
$$

---
class: middle

## Conditioning on covariates


- So we have some statistical variable selection procedure. 

- Transfusion, and length of stay in hospital are on the causal pathway from $X$ to $Y$

- After adjustment, we have an estimated conditional logOR of <br> -0.24 (95% CI -0.41, -0.07)

???

WE may interpret this logOR as evidence that patients treated with iron supplement before hip replacement surgery had lower odds of dying wihtin 90 days of operation.

---
class: middle

## But, the conditional logOR still cannot answer our question: 


--
# What is the survival probability if, 

--
# **contrary to reality**, 

--
# every patient were treated with intravenous iron?


---
class: middle

## Causal languages

1. We ask the question: how $Y$ would react if we could change $X$ and assign it, **contrary to how it was accually assigned.** <br> -- potential outcomes <br>(Neyman, 1923; Rubin, D. 1974)

2. $Y(x)$ is defined as the value that $Y$ would take if $X$ were (hypothetically) set to value of $x$

3. Causal effect is expressed as comparisons between $Y(x)$: <br> $E\{Y(1)\} - E\{Y(0)\}$


---
class: middle

## Potential Causal Estimands - cont. outcome

- Marginal causal mean difference: 

$$E\{Y(1) - Y(0)\}$$
- Conditional causal mean difference:

$$E\{Y(1) - Y(0)|\mathbf{C}\}$$

They are called the **Average Causal/Treatment Effect (ACE or ATE)**. 

---
class: middle

## Potential Causal Estimands - binary outcome

- Marginal causal risk difference:

$$
\text{Pr}[Y(1) = 1] - \text{Pr}[Y(0) = 1]
$$

- Conditional causal log odds ratio:

$$
\log\frac{\text{Pr}(Y(1) = 1, \textbf{C})}{1- \text{Pr}(Y(1) = 1,  \textbf{C})} - \log\frac{\text{Pr}(Y(0) = 1, \textbf{C})}{1- \text{Pr}(Y(0) = 1,  \textbf{C})}
$$

---
class: middle

## Assumption No 1: **no interference**

- Potential value of $Y_i$, does not depend on $X_j$: 

    - $i, j$, are individual indices $\approx$ independent

    - we assume that a (hypothetical) exposure for individual $j$, does not change the outcome of individual $i$


- An example of violation is in the study of vaccines, where vaccinating individual $j$ may affect the disease status of individual $i$.


---
class: middle

## Assumption No 2: **Consistency**

$$
X_i = x \Rightarrow Y_i = Y_i(x)
$$

- For individual $i$, who actually (in the real world) received exposure $x$, their observed outcome is the same as in the hypothetical world that this individual received the same exposure $x$. 


---
class: middle 

## Assuption No 3: <br>**Conditional exchangeability**

- This means we are so *arrogant* and 100% sure that there is **no other unmeasured confounding**.


$$Y(x)\perp \!\!\! \perp X| \textbf{C}, \forall x$$

- $\perp \!\!\! \perp$ means conditional independence; 
    - $A\perp \!\!\! \perp B | C$ means "A is conditionally independent of B given C"
    
- $\forall$ means "for all", here means $x = 0, 1$


???

Conditional on $\mathbf{C}$, the actual exposure level $X$ is independent of the level of the potential outcomes.

---
class: middle, center 

# The end

## slide address: https://wangcc.me/PSA-CSS